# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: microservicegateway
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data  # 添加数据持久化
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9200/_cluster/health?wait_for_status=green&timeout=10s']
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped

volumes:
  elasticsearch_data:
