# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: microservicegateway
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.3
    command: 'start-dev --import-realm'
    volumes:
      # Windows路径挂载方式
      - ./realm-config:/opt/keycloak/data/import
      - ./realm-config/keycloak-health-check.sh:/opt/keycloak/health-check.sh:ro
      - keycloak_data:/opt/keycloak/data
    # 添加user参数解决权限问题
    user: '0:0' # 以root用户运行，解决Windows权限问题
    environment:
      - KC_DB=dev-file
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=scripts
      - KC_HTTP_PORT=9080
      - KC_HTTPS_PORT=9443
      - KC_HEALTH_ENABLED=true
      - KC_HTTP_MANAGEMENT_PORT=9990
      - KC_HOSTNAME_STRICT=false
      - KC_PROXY=edge # 这个很重要，告诉Keycloak它在代理后面
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      # 信任代理的header
      - KC_PROXY_HEADERS=xforwarded
      # 额外的代理配置
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - '9080:9080'
      - '9443:9443'
    healthcheck:
      test: 'bash /opt/keycloak/health-check.sh'
      interval: 10s
      timeout: 10s
      retries: 60
      start_period: 30s
    labels:
      org.springframework.boot.ignore: true
    restart: unless-stopped
volumes:
  keycloak_data:
