# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: microservicegateway
services:
  mysql:
    image: mysql:9.2.0
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
      - mysql_data:/var/lib/mysql  # 添加数据持久化
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_password_123
      - MYSQL_DATABASE=microservicegateway
      - MYSQL_USER=jhipster
      - MYSQL_PASSWORD=jhipster_password
    ports:
      - "3306:3306"
    command: mysqld --lower_case_table_names=1 --skip-mysqlx --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    healthcheck:
      test: ['CMD-SHELL', 'mysql -uroot -pmysql_password_123 -e "SHOW DATABASES;" && sleep 5']
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped

volumes:
  mysql_data:
